baseURL = "https://daluoter.github.io/blog/"
languageCode = "zh-TW"
defaultContentLanguage = "zh"
title = "Blog | 個人作品集"

# Output to /blog/ directory in the main site
publishDir = "../blog"

theme = "techfolio"

[params]
  description = "技術文章與個人筆記"
  author = "Your Name"
  
[languages]
  [languages.zh]
    languageName = "繁體中文"
    weight = 1
    title = "Blog | 個人作品集"
    [languages.zh.params]
      description = "技術文章與個人筆記"
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Blog | Personal Portfolio"
    [languages.en.params]
      description = "Tech articles and personal notes"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "portfolio"
    name = "作品集"
    url = "/#projects"
    weight = 3

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
